### Use TransCAD attributes FROM_LONGI, TO_LONGI, FROM_LAT, TO_LAT to build FromNode ToNode field on LINKS

In [30]:
import geopandas as gpd


nodes = gpd.read_file(r"C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Red Vial Guadalajara\Red Vial Guadalajara\Importacion TransCAD\Nodes\amg_red vial 2023_nodes.shp")
links = gpd.read_file(r"C:\Users\AP03542515\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Red Vial Guadalajara\Red Vial Guadalajara\Importacion TransCAD\Red Vial 2023 Con Velocidades\AMG_RedVial_2023_con_limites_velocidad.shp")

In [31]:
nodes.iloc[0:5].explore()

In [32]:
links.iloc[:5].explore()

In [33]:
nodes

,ID,PARADA,MZONA2023,PESO,CENTROIDE,CALCULO,VIAJESBICI,NODE_ID,geometry
0,99503,NaN,NaN,0.0,NaN,NaN,NaN,99503,POINT (664181.993 2269576.272)
1,71532,1703.0,314.0,1.0,NaN,314.0,NaN,71532,POINT (664152.538 2269429.078)
2,80039,NaN,247.0,0.0,NaN,247.0,NaN,80039,POINT (662496.89 2261746.293)
3,80061,NaN,247.0,0.0,NaN,247.0,NaN,80061,POINT (662427.65 2261741.539)
4,79906,NaN,NaN,0.0,NaN,NaN,NaN,79906,POINT (663035.117 2261120.827)
...,...,...,...,...,...,...,...,...,...
97839,106162,NaN,NaN,NaN,NaN,NaN,NaN,106162,POINT (674970.834 2277604.502)
97840,106163,NaN,NaN,NaN,NaN,NaN,NaN,106163,POINT (674992.3 2277615.574)
97841,106164,NaN,NaN,NaN,NaN,NaN,NaN,106164,POINT (663818.144 2297642.31)
97842,106165,NaN,NaN,NaN,NaN,NaN,NaN,106165,POINT (663917.354 2297623.127)
97843,106166,NaN,NaN,NaN,NaN,NaN,NaN,106166,POINT (663633.564 2297446.103)

In [34]:
links

,ID,LENGTH,DIR,IVTT,DRIVE_TIME,CONST_DRIV,WALK_TIME,CONST_WALK,MODE_WALK,CAPACIDAD,...,CARRILES_M,FROM_LONGI,TO_LONGITU,FROM_LATIT,TO_LATITUD,RELACIONTP,RELACIONT1,Velocidad_,Limite_vel,geometry
0,137214,0.150122,0,0.585476,0.500407,18.0,2.573522,3.5,10.0,2000,...,2.0,-103425398,-103425694,20517824,20516497,15.384615,1.1700,17.999988,30.0,"LINESTRING (664181.993 2269576.272, 664152.538..."
1,5209,0.069408,0,0.278008,0.225108,18.5,1.189857,3.5,10.0,2000,...,2.0,-103442269,-103442933,20447243,20447206,14.979757,1.2350,18.499920,30.0,"LINESTRING (662496.89 2261746.293, 662427.65 2..."
2,5506,2.226424,0,7.235877,5.566059,24.0,38.167264,3.5,10.0,4000,...,2.0,-103437168,-103441080,20441547,20424728,18.461538,1.3000,24.000004,50.0,"LINESTRING (663035.117 2261120.827, 663037.547..."
3,99935,0.015077,0,0.048999,0.037691,24.0,0.258455,3.5,10.0,4000,...,2.0,-103437276,-103437257,20443175,20443040,18.461538,1.3000,24.000955,50.0,"LINESTRING (663022.132 2261300.934, 663024.256..."
4,114741,0.041836,0,0.135966,0.104589,24.0,0.717183,3.5,10.0,4000,...,2.0,-103437208,-103437168,20441923,20441547,18.461538,1.3000,24.000229,50.0,"LINESTRING (663030.547 2261162.409, 663035.117..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139223,145465,0.111282,1,0.417307,0.142062,47.0,1.907691,3.5,10.0,8000,...,4.0,-103320960,-103321397,20589465,20590382,16.000000,2.9375,47.000042,80.0,"LINESTRING (674992.3 2277615.574, 674973.759 2..."
139224,145467,0.082378,0,0.308917,0.308917,16.0,1.412192,3.5,10.0,800,...,2.0,-103425814,-103426280,20771959,20771365,16.000000,1.0000,16.000026,30.0,"LINESTRING (663866.021 2297708.539, 663821.17 ..."
139225,145468,0.057727,0,0.216478,0.216478,16.0,0.989613,3.5,10.0,800,...,2.0,-103425329,-103425351,20771183,20770662,16.000000,1.0000,15.999871,30.0,"LINESTRING (663917.354 2297623.127, 663915.626..."
139226,145469,0.221718,0,0.831444,0.831444,16.0,3.800886,3.5,10.0,800,...,2.0,-103423479,-103421354,20771110,20771237,16.000000,1.0000,15.999971,30.0,"LINESTRING (664110.048 2297616.925, 664331.157..."
139227,145470,0.127977,0,0.479914,0.479914,16.0,2.193895,3.5,10.0,800,...,2.0,-103428071,-103427019,20769609,20769178,16.000000,1.0000,15.999992,30.0,"LINESTRING (663633.564 2297446.103, 663649.66 ..."

In [35]:
links.columns

Index(['ID', 'LENGTH', 'DIR', 'IVTT', 'DRIVE_TIME', 'CONST_DRIV', 'WALK_TIME',
       'CONST_WALK', 'MODE_WALK', 'CAPACIDAD', 'CARRILES', 'ESTACIONAM',
       'MUNICIPIO', 'CALLE', 'TIPO', 'TRANSPORTE', 'JERARQUIA', 'NOMBRE',
       'ABPCE', 'BAPCE', 'TOT_PVC_D', 'TOT_PVM_D', 'ABSPALTO', 'BASPALTO',
       'TOT_SPALTO', 'VOLTP_AB', 'VOLTP_BA', 'VOLTP_TOTA', 'CODIGO',
       'SECUENCIA', 'ANGULO', 'VEL_MOD', 'VEL_ALT', 'CALLEMIN', 'JERARQUIA_',
       'CARGA', 'IDLINK', 'RFJC', 'CAMELLON', 'CARRILES_A', 'CARRILES_B',
       'JERARQUÍA', 'IVTT_BRT', 'IVTT_EXP', 'VOLVP_AB', 'VOLVP_BA',
       'VOLTP2_TOT', 'CARRILES_M', 'FROM_LONGI', 'TO_LONGITU', 'FROM_LATIT',
       'TO_LATITUD', 'RELACIONTP', 'RELACIONT1', 'Velocidad_', 'Limite_vel',
       'geometry'],
      dtype='object')

In [36]:
print("links CRS:", links.crs)
print("nodes CRS:", nodes.crs)

links CRS: EPSG:32613
nodes CRS: EPSG:32613

In [37]:
links

,ID,LENGTH,DIR,IVTT,DRIVE_TIME,CONST_DRIV,WALK_TIME,CONST_WALK,MODE_WALK,CAPACIDAD,...,CARRILES_M,FROM_LONGI,TO_LONGITU,FROM_LATIT,TO_LATITUD,RELACIONTP,RELACIONT1,Velocidad_,Limite_vel,geometry
0,137214,0.150122,0,0.585476,0.500407,18.0,2.573522,3.5,10.0,2000,...,2.0,-103425398,-103425694,20517824,20516497,15.384615,1.1700,17.999988,30.0,"LINESTRING (664181.993 2269576.272, 664152.538..."
1,5209,0.069408,0,0.278008,0.225108,18.5,1.189857,3.5,10.0,2000,...,2.0,-103442269,-103442933,20447243,20447206,14.979757,1.2350,18.499920,30.0,"LINESTRING (662496.89 2261746.293, 662427.65 2..."
2,5506,2.226424,0,7.235877,5.566059,24.0,38.167264,3.5,10.0,4000,...,2.0,-103437168,-103441080,20441547,20424728,18.461538,1.3000,24.000004,50.0,"LINESTRING (663035.117 2261120.827, 663037.547..."
3,99935,0.015077,0,0.048999,0.037691,24.0,0.258455,3.5,10.0,4000,...,2.0,-103437276,-103437257,20443175,20443040,18.461538,1.3000,24.000955,50.0,"LINESTRING (663022.132 2261300.934, 663024.256..."
4,114741,0.041836,0,0.135966,0.104589,24.0,0.717183,3.5,10.0,4000,...,2.0,-103437208,-103437168,20441923,20441547,18.461538,1.3000,24.000229,50.0,"LINESTRING (663030.547 2261162.409, 663035.117..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139223,145465,0.111282,1,0.417307,0.142062,47.0,1.907691,3.5,10.0,8000,...,4.0,-103320960,-103321397,20589465,20590382,16.000000,2.9375,47.000042,80.0,"LINESTRING (674992.3 2277615.574, 674973.759 2..."
139224,145467,0.082378,0,0.308917,0.308917,16.0,1.412192,3.5,10.0,800,...,2.0,-103425814,-103426280,20771959,20771365,16.000000,1.0000,16.000026,30.0,"LINESTRING (663866.021 2297708.539, 663821.17 ..."
139225,145468,0.057727,0,0.216478,0.216478,16.0,0.989613,3.5,10.0,800,...,2.0,-103425329,-103425351,20771183,20770662,16.000000,1.0000,15.999871,30.0,"LINESTRING (663917.354 2297623.127, 663915.626..."
139226,145469,0.221718,0,0.831444,0.831444,16.0,3.800886,3.5,10.0,800,...,2.0,-103423479,-103421354,20771110,20771237,16.000000,1.0000,15.999971,30.0,"LINESTRING (664110.048 2297616.925, 664331.157..."
139227,145470,0.127977,0,0.479914,0.479914,16.0,2.193895,3.5,10.0,800,...,2.0,-103428071,-103427019,20769609,20769178,16.000000,1.0000,15.999992,30.0,"LINESTRING (663633.564 2297446.103, 663649.66 ..."

In [38]:
from_join

,ID,geometry,index_right,NODE_ID,dist_from
0,137214,POINT (664181.993 2269576.272),0,99503,7.982255e-08
1,5209,POINT (662496.89 2261746.293),2,80039,7.751407e-08
2,5506,POINT (663035.117 2261120.827),4,79906,7.878350e-08
3,99935,POINT (663022.132 2261300.934),6,67337,7.889902e-08
4,114741,POINT (663030.547 2261162.409),8,4151,7.901445e-08
...,...,...,...,...,...
139223,145465,POINT (674992.3 2277615.574),97840,106163,1.066090e-07
139224,145467,POINT (663866.021 2297708.539),14550,99037,7.295229e-08
139225,145468,POINT (663917.354 2297623.127),97842,106165,7.313143e-08
139226,145469,POINT (664110.048 2297616.925),14734,99036,7.347725e-08
139227,145470,POINT (663633.564 2297446.103),97843,106166,7.255514e-08

In [39]:
from_points

            ID                        geometry
0       137214  POINT (664181.993 2269576.272)
1         5209   POINT (662496.89 2261746.293)
2         5506  POINT (663035.117 2261120.827)
3        99935  POINT (663022.132 2261300.934)
4       114741  POINT (663030.547 2261162.409)
...        ...                             ...
139223  145465    POINT (674992.3 2277615.574)
139224  145467  POINT (663866.021 2297708.539)
139225  145468  POINT (663917.354 2297623.127)
139226  145469  POINT (664110.048 2297616.925)
139227  145470  POINT (663633.564 2297446.103)

[139228 rows x 2 columns]

In [40]:
nodes

,ID,PARADA,MZONA2023,PESO,CENTROIDE,CALCULO,VIAJESBICI,NODE_ID,geometry
0,99503,NaN,NaN,0.0,NaN,NaN,NaN,99503,POINT (664181.993 2269576.272)
1,71532,1703.0,314.0,1.0,NaN,314.0,NaN,71532,POINT (664152.538 2269429.078)
2,80039,NaN,247.0,0.0,NaN,247.0,NaN,80039,POINT (662496.89 2261746.293)
3,80061,NaN,247.0,0.0,NaN,247.0,NaN,80061,POINT (662427.65 2261741.539)
4,79906,NaN,NaN,0.0,NaN,NaN,NaN,79906,POINT (663035.117 2261120.827)
...,...,...,...,...,...,...,...,...,...
97839,106162,NaN,NaN,NaN,NaN,NaN,NaN,106162,POINT (674970.834 2277604.502)
97840,106163,NaN,NaN,NaN,NaN,NaN,NaN,106163,POINT (674992.3 2277615.574)
97841,106164,NaN,NaN,NaN,NaN,NaN,NaN,106164,POINT (663818.144 2297642.31)
97842,106165,NaN,NaN,NaN,NaN,NaN,NaN,106165,POINT (663917.354 2297623.127)
97843,106166,NaN,NaN,NaN,NaN,NaN,NaN,106166,POINT (663633.564 2297446.103)

In [41]:
links['FROM_LON_deg'] = links['FROM_LONGI'] / 1e6
links['FROM_LAT_deg'] = links['FROM_LATIT'] / 1e6
links['TO_LON_deg']   = links['TO_LONGITU'] / 1e6
links['TO_LAT_deg']   = links['TO_LATITUD'] / 1e6

In [42]:
from_points = gpd.GeoDataFrame(
    links[['ID']].copy(),
    geometry=gpd.points_from_xy(
        links['FROM_LON_deg'],
        links['FROM_LAT_deg']
    ),
    crs="EPSG:4326"
)

to_points = gpd.GeoDataFrame(
    links[['ID']].copy(),
    geometry=gpd.points_from_xy(
        links['TO_LON_deg'],
        links['TO_LAT_deg']
    ),
    crs="EPSG:4326"
)

In [43]:
from_points = from_points.to_crs(links.crs)
to_points   = to_points.to_crs(links.crs)

In [44]:
from_points.iloc[:5].explore()

In [45]:
from_join = gpd.sjoin_nearest(
    from_points,
    nodes[['NODE_ID','geometry']],
    how='left',
    distance_col='dist_from'
)

to_join = gpd.sjoin_nearest(
    to_points,
    nodes[['NODE_ID','geometry']],
    how='left',
    distance_col='dist_to'
)

In [46]:
# --- 4. Pasar resultados a links ---
links = links.merge(
    from_join[['ID', 'NODE_ID']].rename(columns={'NODE_ID': 'fromNode'}),
    on='ID',
    how='left'
)

links = links.merge(
    to_join[['ID', 'NODE_ID']].rename(columns={'NODE_ID': 'toNode'}),
    on='ID',
    how='left'
)

In [48]:
links.to_file("links_cleaned.shp")

C:\Users\AP03542515\AppData\Local\Temp\3\ipykernel_34184\1188474221.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  links.to_file("links_cleaned.shp")
C:\Users\AP03542515\AppData\Local\anaconda3\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'FROM_LON_deg' to 'FROM_LON_d'
  ogr_write(
C:\Users\AP03542515\AppData\Local\anaconda3\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'FROM_LAT_deg' to 'FROM_LAT_d'
  ogr_write(